J = 0.01;
b = 0.1;
K = 0.01;
R = 1;
L = 0.5;
s = tf('s');
G = K/((J*s+b)*(L*s+R)+K^2);

Kp = 100;
Ki = 200;
Kd = 10;
t = 0:0.01:5;
figure;
hold on;
grid on;
C_pid = pid(Kp, Ki, Kd);
sys_cl = feedback(C_pid*G, 1);
step(sys_cl, t);
title('Step Response with PID Controller');
legend(sprintf('Kp = %.1f, Ki = %.1f, Kd = %.1f', Kp, Ki, Kd));
figure;
hold on;
grid on;
disturbance = 0.1/s;
sys_cl_dist = feedback(C_pid*G, 1);
sys_cl_disturbed = sys_cl_dist + disturbance;
step(sys_cl_disturbed, t);
title('Response to Disturbance with PID Controller');
legend(sprintf('Kp = %.1f, Ki = %.1f, Kd = %.1f', Kp, Ki, Kd));
